import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

interface Props {
	position: [number, number, number];
}

export default function Apple({ position }: Props) {
	const group = useRef();
	// @ts-ignore
	const { nodes } = useGLTF('/apple/scene.gltf');

	return (
		<group ref={group} dispose={null}>
			<group scale={[0.03, 0.03, 0.03]} position={position} rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group position={[3.86, 0, -4.23]}>
						<mesh
							castShadow
							// receiveShadow
							geometry={nodes['Sphere07_Material_#25_0'].geometry}
							material={nodes['Sphere07_Material_#25_0'].material}
						/>
					</group>
					<group name='Cylinder05' position={[3.86, 0, -4.23]}>
						<mesh
							castShadow
							// receiveShadow
							geometry={nodes['Cylinder05_Material_#25_0'].geometry}
							material={nodes['Cylinder05_Material_#25_0'].material}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cedricmahot (https://sketchfab.com/cedricmahot)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/b496adbf9b924ff99939ad38330eb3cf
title: Apple FBX
*/
useGLTF.preload('/apple/scene.gltf');
