// import {} from 'three';
import { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		body_body1_0: THREE.SkinnedMesh;
		front_legs_front_legs_0: THREE.SkinnedMesh;
		small_legs_small_legs_0: THREE.SkinnedMesh;
		_rootJoint: THREE.Bone;
	};
	materials: {
		body1: THREE.MeshStandardMaterial;
		front_legs: THREE.MeshStandardMaterial;
		small_legs: THREE.MeshStandardMaterial;
	};
};

/**
 * The Exe Model
 */
export default function Exe() {
	const group = useRef<THREE.Group>();
	const { nodes, materials, animations } = useGLTF('/exe/scene.gltf') as GLTFResult;

	const { actions } = useAnimations<any>(animations, group);

	// Run the animation
	useEffect(() => {
		actions!.Idle?.play();
	}, [actions]);

	return (
		<group ref={group} dispose={null}>
			{/* position={position} */}
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group position={[0.07, 0.84, -1000.1]} rotation={[0, -Math.PI / 2, 0]} />
					<group name='Root1' position={[0, 0.49, -0.09]}>
						<group position={[0.42, 0, 0.22]} rotation={[0, -1.1, 0]}>
							<group position={[0.27, 0, 0]} />
						</group>
						<group position={[0.38, 0.03, 0]} rotation={[0, 0, -0.05]}>
							<group position={[0.17, -0.21, 0.02]} />
						</group>
						<group position={[0.38, 0.03, -0.18]} rotation={[0, 0.72, -0.04]}>
							<group position={[0.17, -0.21, -0.01]} />
						</group>
						<group position={[-0.38, 0.03, -0.18]} rotation={[0, -0.74, 0.05]}>
							<group position={[-0.16, -0.21, -0.01]} />
						</group>
						<group position={[-0.38, 0.03, 0]} rotation={[0, 0, 0.05]}>
							<group position={[-0.17, -0.21, 0.02]} />
						</group>
						<group position={[-0.42, 0, 0.22]} rotation={[0, 1.05, 0]}>
							<group position={[-0.27, 0, 0]} />
						</group>
						<primitive object={nodes._rootJoint} />
						<group position={[-0.2, 0.63, -0.33]}>
							<group position={[0, 0.12, 0]}>
								<group position={[0, 0.12, 0]} />
							</group>
						</group>
						<skinnedMesh
							castShadow
							geometry={nodes.body_body1_0.geometry}
							material={materials.body1}
							skeleton={nodes.body_body1_0.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.front_legs_front_legs_0.geometry}
							material={materials.front_legs}
							skeleton={nodes.front_legs_front_legs_0.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.small_legs_small_legs_0.geometry}
							material={materials.small_legs}
							skeleton={nodes.small_legs_small_legs_0.skeleton}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Trent Rivers (https://sketchfab.com/tbrivers)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/23faa9598a9a4749bd2f54a1946eb227
title: Bug Bot
*/

useGLTF.preload('/exe/scene.gltf');
